name: Android CI

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Decode Release Keystore
      run: echo ${{ secrets.RELEASE_KEYSTORE }} | base64 -d > release.jks

    - name: Decode Debug Keystore
      run: echo ${{ secrets.DEBUG_KEYSTORE }} | base64 -d > debug.jks

    - name: Decode google-services.json
      run: echo ${{ secrets.GOOGLE_SERVICES_JSON }} | base64 -d > app/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Update local.properties - Supabase URL
      run: echo 'SUPABASE_URL=${{ secrets.SUPABASE_URL }}' > ./local.properties
    - name: Update local.properties - Supabase KEY
      run: echo 'SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}' >> ./local.properties
    - name: Update local.properties - RELEASE_STORE_FILE
      run: echo 'RELEASE_STORE_FILE=${{ vars.RELEASE_STORE_FILE }}' >> ./local.properties
    - name: Update local.properties - RELEASE_STORE_PASSWORD
      run: echo 'RELEASE_STORE_PASSWORD=${{ vars.RELEASE_STORE_PASSWORD }}' >> ./local.properties
    - name: Update local.properties - RELEASE_KEY_ALIAS
      run: echo 'RELEASE_KEY_ALIAS=${{ vars.RELEASE_KEY_ALIAS }}' >> ./local.properties
    - name: Update local.properties - RELEASE_KEY_PASSWORD
      run: echo 'RELEASE_KEY_PASSWORD=${{ vars.RELEASE_KEY_PASSWORD }}' >> ./local.properties

    - name: Update local.properties - DEBUG_STORE_FILE
      run: echo 'DEBUG_STORE_FILE=${{ vars.DEBUG_STORE_FILE }}' >> ./local.properties
    - name: Update local.properties - DEBUG_STORE_PASSWORD
      run: echo 'DEBUG_STORE_PASSWORD=${{ vars.DEBUG_STORE_PASSWORD }}' >> ./local.properties
    - name: Update local.properties - RELEASE_KEY_ALIAS
      run: echo 'DEBUG_KEY_ALIAS=${{ vars.DEBUG_KEY_ALIAS }}' >> ./local.properties
    - name: Update local.properties - DEBUG_KEY_PASSWORD
      run: echo 'DEBUG_KEY_PASSWORD=${{ vars.DEBUG_KEY_PASSWORD }}' >> ./local.properties

    - name: Install Fastlane
      run: gem install fastlane

    - name: Install Fastlane plugins
      run: fastlane add_plugin firebase_app_distribution
      
    - name: Run tests
      run: fastlane android test

    - name: Fastlane build for Firebase Distribution
      run: fastlane android beta
      env:
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
